parameters:
    app_language: "%env(APP_LANGUAGE)%"
    cards_language: "%env(CARDS_LANGUAGE)%"

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $emailFromAddress: '%env(MAILER_FROM_ADDRESS)%'
            $emailFromName: '%env(MAILER_FROM_NAME)%'

    App\Service\LanguageManager:
        arguments:
            $defaultAppLanguage: "%app_language%"
            $defaultCardsLanguage: "%cards_language%"

    App\:
        resource: '../src/'
